# Generated by Django 3.1.2 on 2020-10-07 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kukai', '0002_ku_selected_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ku',
            name='selected_by',
        ),
        migrations.AddField(
            model_name='ku',
            name='selectors',
            field=models.ManyToManyField(blank=True, related_name='selected_ku_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
