# Generated by Django 3.1.2 on 2020-10-07 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kukai', '0003_auto_20201008_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='unza',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_kukai', to=settings.AUTH_USER_MODEL),
        ),
    ]
