# Generated by Django 3.1.2 on 2020-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukai', '0005_auto_20201008_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='unza',
            name='info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
